using System.Text.RegularExpressions;

namespace Edulytics.Services.LessonContent;

/// <summary>
/// Deterministic learner-facing Polish localization for Mathematics-engine prose.
/// Mathematical symbols, numbers and variable names are preserved; only authored
/// prompt/solution language is localized. This is deliberately finite and
/// reviewable so Polish Rich V2 never depends on a runtime machine translator.
/// </summary>
public static class PolishMathematicsTextLocalizer
{
    private static readonly (Regex Pattern, string Replacement)[] PhraseRules =
    [
        R(@"\bHow many\b", "Ile"),
        R(@"\bWhat is\b", "Ile wynosi"),
        R(@"\bWhich of the following\b", "Która z poniższych odpowiedzi"),
        R(@"\bWhich statement\b", "Które stwierdzenie"),
        R(@"\bFind the value of\b", "Wyznacz wartość"),
        R(@"\bFind the\b", "Wyznacz"),
        R(@"\bFind\b", "Wyznacz"),
        R(@"\bCalculate\b", "Oblicz"),
        R(@"\bEvaluate\b", "Oblicz"),
        R(@"\bSolve for\b", "Rozwiąż równanie względem"),
        R(@"\bSolve\b", "Rozwiąż"),
        R(@"\bSimplify\b", "Uprość"),
        R(@"\bRound\b", "Zaokrąglij"),
        R(@"\bCompare\b", "Porównaj"),
        R(@"\bOrder\b", "Uporządkuj"),
        R(@"\bDetermine\b", "Wyznacz"),
        R(@"\bWrite\b", "Zapisz"),
        R(@"\bState\b", "Podaj"),
        R(@"\bChoose\b", "Wybierz"),
        R(@"\bEnter true or false\b", "Wpisz „prawda” albo „fałsz”"),
        R(@"\btrue or false\b", "prawda albo fałsz"),
        R(@"\bas a simplified fraction\b", "jako ułamek nieskracalny"),
        R(@"\bas a fraction\b", "jako ułamek"),
        R(@"\bto the nearest\b", "do najbliższej wartości"),
        R(@"\bfrom x=0 to x=\b", "od x=0 do x="),
        R(@"\bfrom\b", "od"),
        R(@"\bbetween\b", "między"),
        R(@"\bgreater than\b", "większe niż"),
        R(@"\bless than\b", "mniejsze niż"),
        R(@"\bequal to\b", "równe"),
        R(@"\bis equal to\b", "jest równe"),
        R(@"\bare equal\b", "są równe"),
        R(@"\bnot equal\b", "nierówne"),
        R(@"\bright triangle\b", "trójkącie prostokątnym"),
        R(@"\brectangular prism\b", "prostopadłościan"),
        R(@"\bperpendicular height\b", "wysokość prostopadła"),
        R(@"\bperpendicular bisector\b", "symetralna odcinka"),
        R(@"\bcommon denominator\b", "wspólny mianownik"),
        R(@"\bcommon factor\b", "wspólny dzielnik"),
        R(@"\bgreatest common factor\b", "największy wspólny dzielnik"),
        R(@"\bleast common multiple\b", "najmniejszą wspólną wielokrotność"),
        R(@"\bprime factorisation\b", "rozkład na czynniki pierwsze"),
        R(@"\bprime factorization\b", "rozkład na czynniki pierwsze"),
        R(@"\bplace value\b", "wartość pozycyjna"),
        R(@"\bnumber line\b", "oś liczbowa"),
        R(@"\bunit rate\b", "wartość jednostkowa"),
        R(@"\bscale factor\b", "skala podobieństwa"),
        R(@"\binterior angles\b", "kąty wewnętrzne"),
        R(@"\binterior angle\b", "kąt wewnętrzny"),
        R(@"\bvertical angles\b", "kąty wierzchołkowe"),
        R(@"\bparallel lines\b", "proste równoległe"),
        R(@"\bsupplementary angles\b", "kąty dopełniające się do 180°"),
        R(@"\bmidpoint\b", "środek odcinka"),
        R(@"\bgradient\b", "współczynnik kierunkowy"),
        R(@"\by-intercept\b", "punkt przecięcia z osią y"),
        R(@"\bx-intercept\b", "punkt przecięcia z osią x"),
        R(@"\bcircumference\b", "obwód"),
        R(@"\bsurface area\b", "pole powierzchni"),
        R(@"\barea\b", "pole"),
        R(@"\bvolume\b", "objętość"),
        R(@"\bprobability\b", "prawdopodobieństwo"),
        R(@"\bmean\b", "średnią"),
        R(@"\bmedian\b", "medianę"),
        R(@"\brange\b", "rozstęp"),
        R(@"\barithmetic sequence\b", "ciąg arytmetyczny"),
        R(@"\bgeometric sequence\b", "ciąg geometryczny"),
        R(@"\bconstant difference\b", "stałą różnicę"),
        R(@"\bconstant ratio\b", "stały iloraz"),
        R(@"\bdefinite integral\b", "całkę oznaczoną"),
        R(@"\bderivative\b", "pochodną"),
        R(@"\bantiderivative\b", "funkcję pierwotną"),
        R(@"\bminimum\b", "minimum"),
        R(@"\bmaximum\b", "maksimum"),
        R(@"\breal part\b", "część rzeczywistą"),
        R(@"\bimaginary part\b", "część urojoną"),
        R(@"\binitial velocity\b", "prędkość początkową"),
        R(@"\bfinal velocity\b", "prędkość końcową"),
        R(@"\bconstant acceleration\b", "stałe przyspieszenie"),
        R(@"\bfavourable outcomes\b", "wyniki sprzyjające"),
        R(@"\bfavorable outcomes\b", "wyniki sprzyjające"),
        R(@"\bequally likely outcomes\b", "jednakowo prawdopodobne wyniki"),
        R(@"\bsample space\b", "przestrzeń zdarzeń"),
        R(@"\bunordered pairs\b", "nieuporządkowanych par"),
        R(@"\btranslation vector\b", "wektor przesunięcia"),
        R(@"\btranslation\b", "przesunięcie"),
        R(@"\breflection\b", "odbicie"),
        R(@"\brotation\b", "obrót"),
        R(@"\bclockwise\b", "zgodnie z ruchem wskazówek zegara"),
        R(@"\banticlockwise\b", "przeciwnie do ruchu wskazówek zegara"),
        R(@"\bcounterclockwise\b", "przeciwnie do ruchu wskazówek zegara"),
        R(@"\bhorizontal distance\b", "odległość poziomą"),
        R(@"\bvertical distance\b", "odległość pionową"),
        R(@"\bexactly one\b", "dokładnie jeden"),
        R(@"\bat least\b", "co najmniej"),
        R(@"\bat most\b", "co najwyżej"),
        R(@"\bper cent\b", "procent"),
        R(@"\bpercent\b", "procent"),
        R(@"\bpercentage\b", "procent"),
        R(@"\bincrease by\b", "zwiększ o"),
        R(@"\bdecrease by\b", "zmniejsz o"),
        R(@"\bof a quantity\b", "z danej wielkości"),
        R(@"\bof the quantity\b", "z danej wielkości"),
        R(@"\bof the number\b", "z liczby"),
        R(@"\bof\b", "z"),
        R(@"\bUse the formula\b", "Zastosuj wzór"),
        R(@"\bUse\b", "Użyj"),
        R(@"\bSubstitute into both original equations\b", "Podstaw do obu pierwotnych równań"),
        R(@"\bSubstitute into the original equation\b", "Podstaw do pierwotnego równania"),
        R(@"\bSubstitute back\b", "Podstaw wynik z powrotem"),
        R(@"\bSubstitute\b", "Podstaw"),
        R(@"\bExpand\b", "Rozwiń"),
        R(@"\bFactorise\b", "Rozłóż na czynniki"),
        R(@"\bFactorize\b", "Rozłóż na czynniki"),
        R(@"\bMultiply\b", "Pomnóż"),
        R(@"\bDivide\b", "Podziel"),
        R(@"\bAdd\b", "Dodaj"),
        R(@"\bSubtract\b", "Odejmij"),
        R(@"\bCheck\b", "Sprawdź"),
        R(@"\bConvert\b", "Przelicz"),
        R(@"\bIdentify\b", "Rozpoznaj"),
        R(@"\bApply\b", "Zastosuj"),
        R(@"\bThe answer is\b", "Odpowiedź to"),
        R(@"\bThe result is\b", "Wynik to"),
        R(@"\bThe question asks\b", "Pytanie dotyczy"),
        R(@"\bthe requested\b", "wymagany"),
        R(@"\bthe original\b", "pierwotny"),
        R(@"\bthe same\b", "ten sam"),
        R(@"\bthe total\b", "suma"),
        R(@"\bthe value\b", "wartość"),
        R(@"\bthe number\b", "liczba"),
        R(@"\bthe angle\b", "kąt"),
        R(@"\bthe side\b", "bok"),
        R(@"\bthe base\b", "podstawa"),
        R(@"\bthe height\b", "wysokość"),
        R(@"\bthe radius\b", "promień"),
        R(@"\bthe diameter\b", "średnica"),
        R(@"\bthe denominator\b", "mianownik"),
        R(@"\bthe numerator\b", "licznik"),
        R(@"\bthe exponent\b", "wykładnik"),
        R(@"\bthe coefficient\b", "współczynnik"),
        R(@"\bthe equation\b", "równanie"),
        R(@"\bthe expression\b", "wyrażenie"),
        R(@"\bthe function\b", "funkcja"),
        R(@"\bthe sequence\b", "ciąg"),
        R(@"\bthe fraction\b", "ułamek"),
        R(@"\bthe decimal\b", "liczba dziesiętna"),
        R(@"\bthe remainder\b", "reszta"),
        R(@"\bthe difference\b", "różnica"),
        R(@"\bthe product\b", "iloczyn"),
        R(@"\bthe quotient\b", "iloraz"),
        R(@"\bthe sum\b", "suma"),
        R(@"\bthen\b", "następnie"),
        R(@"\bfirst\b", "najpierw"),
        R(@"\bnext\b", "następnie"),
        R(@"\bfinally\b", "na końcu"),
        R(@"\bbecause\b", "ponieważ"),
        R(@"\btherefore\b", "dlatego"),
        R(@"\bso\b", "więc")
    ];

    private static readonly IReadOnlyDictionary<string, string> WordMap =
        new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            ["a"] = "",
            ["an"] = "",
            ["the"] = "",
            ["and"] = "i",
            ["or"] = "lub",
            ["with"] = "z",
            ["without"] = "bez",
            ["into"] = "do",
            ["both"] = "obu",
            ["original"] = "pierwotny",
            ["in"] = "w",
            ["on"] = "na",
            ["at"] = "przy",
            ["for"] = "dla",
            ["to"] = "do",
            ["by"] = "przez",
            ["where"] = "gdzie",
            ["when"] = "gdy",
            ["what"] = "co",
            ["which"] = "który",
            ["how"] = "jak",
            ["if"] = "jeśli",
            ["is"] = "jest",
            ["are"] = "są",
            ["has"] = "ma",
            ["have"] = "mają",
            ["each"] = "każdy",
            ["every"] = "każdy",
            ["one"] = "jeden",
            ["two"] = "dwa",
            ["three"] = "trzy",
            ["four"] = "cztery",
            ["number"] = "liczba",
            ["numbers"] = "liczby",
            ["value"] = "wartość",
            ["values"] = "wartości",
            ["digit"] = "cyfra",
            ["digits"] = "cyfry",
            ["place"] = "pozycja",
            ["places"] = "pozycje",
            ["power"] = "potęga",
            ["powers"] = "potęgi",
            ["ten"] = "dziesięć",
            ["whole"] = "całość",
            ["quantity"] = "wielkość",
            ["quantities"] = "wielkości",
            ["fraction"] = "ułamek",
            ["fractions"] = "ułamki",
            ["numerator"] = "licznik",
            ["denominator"] = "mianownik",
            ["decimal"] = "dziesiętny",
            ["decimals"] = "liczby dziesiętne",
            ["ratio"] = "stosunek",
            ["rate"] = "wartość",
            ["equivalent"] = "równoważny",
            ["equation"] = "równanie",
            ["equations"] = "równania",
            ["inequality"] = "nierówność",
            ["expression"] = "wyrażenie",
            ["expressions"] = "wyrażenia",
            ["function"] = "funkcja",
            ["functions"] = "funkcje",
            ["sequence"] = "ciąg",
            ["sequences"] = "ciągi",
            ["series"] = "szereg",
            ["term"] = "wyraz",
            ["terms"] = "wyrazy",
            ["angle"] = "kąt",
            ["angles"] = "kąty",
            ["triangle"] = "trójkąt",
            ["square"] = "kwadrat",
            ["rectangle"] = "prostokąt",
            ["circle"] = "okrąg",
            ["radius"] = "promień",
            ["diameter"] = "średnica",
            ["side"] = "bok",
            ["sides"] = "boki",
            ["length"] = "długość",
            ["width"] = "szerokość",
            ["height"] = "wysokość",
            ["base"] = "podstawa",
            ["point"] = "punkt",
            ["points"] = "punkty",
            ["line"] = "prosta",
            ["lines"] = "proste",
            ["axis"] = "oś",
            ["coordinates"] = "współrzędne",
            ["coordinate"] = "współrzędna",
            ["vector"] = "wektor",
            ["vectors"] = "wektory",
            ["matrix"] = "macierz",
            ["determinant"] = "wyznacznik",
            ["mean"] = "średnia",
            ["median"] = "mediana",
            ["range"] = "rozstęp",
            ["frequency"] = "liczebność",
            ["frequencies"] = "liczebności",
            ["outcomes"] = "wyniki",
            ["outcome"] = "wynik",
            ["event"] = "zdarzenie",
            ["events"] = "zdarzenia",
            ["probability"] = "prawdopodobieństwo",
            ["total"] = "suma",
            ["result"] = "wynik",
            ["answer"] = "odpowiedź",
            ["given"] = "dany",
            ["same"] = "ten sam",
            ["requested"] = "wymagany",
            ["simplified"] = "uproszczony",
            ["distinct"] = "różne",
            ["represented"] = "przedstawiony",
            ["represents"] = "przedstawia",
            ["occurred"] = "zaszło",
            ["also"] = "także",
            ["only"] = "tylko",
            ["method"] = "metoda",
            ["step"] = "krok",
            ["steps"] = "kroki",
            ["factor"] = "czynnik",
            ["factors"] = "czynniki",
            ["multiple"] = "wielokrotność",
            ["multiples"] = "wielokrotności",
            ["remainder"] = "reszta",
            ["difference"] = "różnica",
            ["product"] = "iloczyn",
            ["quotient"] = "iloraz",
            ["sum"] = "suma",
            ["equal"] = "równe",
            ["greater"] = "większe",
            ["less"] = "mniejsze",
            ["positive"] = "dodatnie",
            ["negative"] = "ujemne",
            ["acute"] = "ostry",
            ["right"] = "prosty",
            ["obtuse"] = "rozwarty",
            ["straight"] = "półpełny",
            ["reflex"] = "wklęsły",
            ["true"] = "prawda",
            ["false"] = "fałsz",
            ["yes"] = "tak",
            ["no"] = "nie",
            ["days"] = "dni",
            ["day"] = "dzień",
            ["hours"] = "godziny",
            ["hour"] = "godzina",
            ["minutes"] = "minuty",
            ["minute"] = "minuta",
            ["objects"] = "obiekty",
            ["object"] = "obiekt",
            ["groups"] = "grupy",
            ["group"] = "grupa",
            ["parts"] = "części",
            ["part"] = "część",
            ["remaining"] = "pozostałe",
            ["starts"] = "zaczyna się",
            ["start"] = "początek",
            ["ends"] = "kończy się",
            ["end"] = "koniec",
            ["moves"] = "przesuwa się",
            ["move"] = "przesuń",
            ["left"] = "lewo",
            ["right"] = "prawo",
            ["up"] = "górę",
            ["down"] = "dół"
        };

    private static readonly IReadOnlyDictionary<string, string> IdentifierTokens =
        new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            ["supporting"] = "",
            ["number"] = "liczby",
            ["whole"] = "całkowite",
            ["add"] = "dodawanie",
            ["subtract"] = "odejmowanie",
            ["multiply"] = "mnożenie",
            ["divide"] = "dzielenie",
            ["fractions"] = "ułamki",
            ["fraction"] = "ułamek",
            ["compare"] = "porównywanie",
            ["equivalent"] = "równoważność",
            ["quantity"] = "wielkości",
            ["decimals"] = "liczby dziesiętne",
            ["percentages"] = "procenty",
            ["ratio"] = "stosunki",
            ["unit"] = "jednostkowe",
            ["rate"] = "wartości",
            ["algebra"] = "algebra",
            ["linear"] = "liniowe",
            ["inequality"] = "nierówności",
            ["geometry"] = "geometria",
            ["coordinate"] = "współrzędne",
            ["angles"] = "kąty",
            ["polygons"] = "wielokąty",
            ["similarity"] = "podobieństwo",
            ["perimeter"] = "obwód",
            ["area"] = "pole",
            ["right"] = "prostokątny",
            ["triangle"] = "trójkąt",
            ["statistics"] = "statystyka",
            ["probability"] = "prawdopodobieństwo",
            ["theoretical"] = "teoretyczne",
            ["mean"] = "średnia",
            ["median"] = "mediana",
            ["range"] = "rozstęp",
            ["measurement"] = "miary",
            ["functions"] = "funkcje",
            ["sequences"] = "ciągi",
            ["series"] = "szeregi",
            ["trigonometry"] = "trygonometria",
            ["calculus"] = "analiza",
            ["vectors"] = "wektory",
            ["surds"] = "pierwiastki",
            ["indices"] = "potęgi",
            ["exponentials"] = "funkcje wykładnicze",
            ["logarithms"] = "logarytmy",
            ["combinatorics"] = "kombinatoryka",
            ["transformations"] = "przekształcenia",
            ["reasoning"] = "rozumowanie",
            ["direct"] = "bezpośrednie",
            ["exact"] = "dokładne",
            ["build"] = "budowanie",
            ["apply"] = "zastosowanie",
            ["core"] = "podstawowe",
            ["mixed"] = "mieszane",
            ["solve"] = "rozwiązywanie",
            ["evaluate"] = "obliczanie",
            ["simplify"] = "upraszczanie",
            ["round"] = "zaokrąglanie",
            ["rounding"] = "zaokrąglanie",
            ["position"] = "położenie",
            ["direction"] = "kierunek",
            ["shape"] = "figury",
            ["dimension"] = "wymiar",
            ["time"] = "czas",
            ["money"] = "pieniądze",
            ["conversion"] = "przeliczanie",
            ["charts"] = "wykresy",
            ["collection"] = "zbieranie danych",
            ["standard"] = "standardowa",
            ["form"] = "postać",
            ["power10"] = "potęgi dziesięciu"
        };

    public static string Localize(string? text)
    {
        var value = Regex.Replace(text ?? string.Empty, @"\s+", " ").Trim();
        if (value.Length == 0)
            return string.Empty;

        foreach (var (pattern, replacement) in PhraseRules)
            value = pattern.Replace(value, replacement);

        value = Regex.Replace(
            value,
            @"\b[A-Za-z][A-Za-z'-]*\b",
            match => WordMap.TryGetValue(match.Value, out var replacement)
                ? replacement
                : match.Value,
            RegexOptions.CultureInvariant);

        value = Regex.Replace(value, @"\s+([,.;:!?])", "$1");
        value = Regex.Replace(value, @"\s{2,}", " ").Trim();
        return value;
    }

    public static string LocalizeAnswer(string? answer)
    {
        var value = (answer ?? string.Empty).Trim();
        return value.ToLowerInvariant() switch
        {
            "perpendicular bisector" => "symetralna odcinka",
            "positive" => "dodatnia",
            "negative" => "ujemna",
            "equal" => "równe",
            "acute" => "ostry",
            "right" => "prosty",
            "obtuse" => "rozwarty",
            "straight" => "półpełny",
            "reflex" => "wklęsły",
            "true" => "prawda",
            "false" => "fałsz",
            "yes" => "tak",
            "no" => "nie",
            _ => Localize(value)
        };
    }

    public static string FamilyLabel(string family) =>
        HumanizeIdentifier(family);

    public static string SkillLabel(string skill) =>
        HumanizeIdentifier(skill);

    private static string HumanizeIdentifier(string value)
    {
        var tokens = value
            .Split('.', StringSplitOptions.RemoveEmptyEntries)
            .SelectMany(token => token.Split(
                ['_', '-'],
                StringSplitOptions.RemoveEmptyEntries))
            .Select(token =>
                IdentifierTokens.TryGetValue(token, out var localized)
                    ? localized
                    : token)
            .Where(token => !string.IsNullOrWhiteSpace(token))
            .ToArray();

        return tokens.Length == 0
            ? "zweryfikowany przypadek matematyczny"
            : string.Join(" ", tokens);
    }

    private static (Regex Pattern, string Replacement) R(
        string pattern,
        string replacement) =>
        (
            new Regex(
                pattern,
                RegexOptions.IgnoreCase |
                RegexOptions.CultureInvariant |
                RegexOptions.Compiled),
            replacement
        );
}
