namespace Edulytics.Data.Seeding;

/// <summary>
/// Exact allow-list for the reviewed Common Core official-outcome closure.
/// Production may replace stale pedagogical outcome rows only for these
/// 94 stable lesson identities; every other Common Core lesson stays fail-closed.
/// </summary>
public static class CommonCoreOfficialOutcomeMappingCorrections
{
    private static readonly HashSet<string> LessonCodes =
        new(StringComparer.Ordinal)
        {
            "PED:US-CCSS-MATH:G1:U07:L01",
            "PED:US-CCSS-MATH:G1:U07:L03",
            "PED:US-CCSS-MATH:G2:U01:L07",
            "PED:US-CCSS-MATH:G2:U03:L01",
            "PED:US-CCSS-MATH:G2:U08:L01",
            "PED:US-CCSS-MATH:G3:U01:L01",
            "PED:US-CCSS-MATH:G3:U01:L02",
            "PED:US-CCSS-MATH:G3:U01:L03",
            "PED:US-CCSS-MATH:G3:U03:L01",
            "PED:US-CCSS-MATH:G3:U06:L16",
            "PED:US-CCSS-MATH:G3:U07:L01",
            "PED:US-CCSS-MATH:G3:U08:L06",
            "PED:US-CCSS-MATH:G3:U08:L12",
            "PED:US-CCSS-MATH:G4:U02:L01",
            "PED:US-CCSS-MATH:G4:U02:L02",
            "PED:US-CCSS-MATH:G4:U02:L03",
            "PED:US-CCSS-MATH:G4:U02:L06",
            "PED:US-CCSS-MATH:G4:U02:L17",
            "PED:US-CCSS-MATH:G4:U03:L15",
            "PED:US-CCSS-MATH:G4:U05:L01",
            "PED:US-CCSS-MATH:G5:U03:L10",
            "PED:US-CCSS-MATH:G5:U04:L01",
            "PED:US-CCSS-MATH:G5:U04:L02",
            "PED:US-CCSS-MATH:G5:U04:L10",
            "PED:US-CCSS-MATH:G5:U06:L01",
            "PED:US-CCSS-MATH:G6:U01:L01",
            "PED:US-CCSS-MATH:G6:U03:L02",
            "PED:US-CCSS-MATH:G6:U03:L17",
            "PED:US-CCSS-MATH:G6:U04:L01",
            "PED:US-CCSS-MATH:G6:U04:L02",
            "PED:US-CCSS-MATH:G6:U04:L03",
            "PED:US-CCSS-MATH:G6:U05:L01",
            "PED:US-CCSS-MATH:G6:U05:L05",
            "PED:US-CCSS-MATH:G6:U05:L06",
            "PED:US-CCSS-MATH:G6:U05:L09",
            "PED:US-CCSS-MATH:G6:U06:L01",
            "PED:US-CCSS-MATH:G6:U06:L03",
            "PED:US-CCSS-MATH:G6:U06:L09",
            "PED:US-CCSS-MATH:G6:U08:L01",
            "PED:US-CCSS-MATH:G6:U09:L01",
            "PED:US-CCSS-MATH:G6:U09:L02",
            "PED:US-CCSS-MATH:G6:U09:L03",
            "PED:US-CCSS-MATH:G7:U04:L01",
            "PED:US-CCSS-MATH:G7:U06:L01",
            "PED:US-CCSS-MATH:G7:U06:L13",
            "PED:US-CCSS-MATH:G7:U06:L15",
            "PED:US-CCSS-MATH:G7:U06:L23",
            "PED:US-CCSS-MATH:G7:U07:L01",
            "PED:US-CCSS-MATH:G7:U09:L10",
            "PED:US-CCSS-MATH:G8:U01:L01",
            "PED:US-CCSS-MATH:G8:U01:L17",
            "PED:US-CCSS-MATH:G8:U02:L01",
            "PED:US-CCSS-MATH:G8:U02:L02",
            "PED:US-CCSS-MATH:G8:U02:L03",
            "PED:US-CCSS-MATH:G8:U03:L01",
            "PED:US-CCSS-MATH:G8:U03:L05",
            "PED:US-CCSS-MATH:G8:U03:L06",
            "PED:US-CCSS-MATH:G8:U03:L07",
            "PED:US-CCSS-MATH:G8:U03:L09",
            "PED:US-CCSS-MATH:G8:U03:L10",
            "PED:US-CCSS-MATH:G8:U03:L12",
            "PED:US-CCSS-MATH:G8:U04:L01",
            "PED:US-CCSS-MATH:G8:U04:L02",
            "PED:US-CCSS-MATH:G8:U05:L12",
            "PED:US-CCSS-MATH:G8:U06:L11",
            "PED:US-CCSS-MATH:G8:U07:L01",
            "PED:US-CCSS-MATH:G8:U08:L06",
            "PED:US-CCSS-MATH:G8:U09:L01",
            "PED:US-CCSS-MATH:G8:U09:L03",
            "PED:US-CCSS-MATH:G8:U09:L05",
            "PED:US-CCSS-MATH:G8:U09:L06",
            "PED:US-CCSS-MATH:HS:TRAD:ALG1:IM-1E:U01:L01",
            "PED:US-CCSS-MATH:HS:TRAD:ALG1:IM-1E:U01:L05",
            "PED:US-CCSS-MATH:HS:TRAD:ALG1:IM-1E:U01:L06",
            "PED:US-CCSS-MATH:HS:TRAD:ALG1:IM-1E:U01:L07",
            "PED:US-CCSS-MATH:HS:TRAD:ALG1:IM-1E:U01:L08",
            "PED:US-CCSS-MATH:HS:TRAD:ALG1:IM-1E:U05:L14",
            "PED:US-CCSS-MATH:HS:TRAD:ALG2:IM-1E:U01:L01",
            "PED:US-CCSS-MATH:HS:TRAD:ALG2:IM-1E:U01:L02",
            "PED:US-CCSS-MATH:HS:TRAD:ALG2:IM-1E:U01:L03",
            "PED:US-CCSS-MATH:HS:TRAD:ALG2:IM-1E:U01:L04",
            "PED:US-CCSS-MATH:HS:TRAD:ALG2:IM-1E:U02:L08",
            "PED:US-CCSS-MATH:HS:TRAD:ALG2:IM-1E:U02:L09",
            "PED:US-CCSS-MATH:HS:TRAD:ALG2:IM-1E:U02:L13",
            "PED:US-CCSS-MATH:HS:TRAD:ALG2:IM-1E:U03:L01",
            "PED:US-CCSS-MATH:HS:TRAD:ALG2:IM-1E:U03:L02",
            "PED:US-CCSS-MATH:HS:TRAD:ALG2:IM-1E:U06:L01",
            "PED:US-CCSS-MATH:HS:TRAD:ALG2:IM-1E:U06:L02",
            "PED:US-CCSS-MATH:HS:TRAD:ALG2:IM-1E:U06:L07",
            "PED:US-CCSS-MATH:HS:TRAD:GEO:IM-1E:U02:L11",
            "PED:US-CCSS-MATH:HS:TRAD:GEO:IM-1E:U03:L10",
            "PED:US-CCSS-MATH:HS:TRAD:GEO:IM-1E:U05:L12",
            "PED:US-CCSS-MATH:HS:TRAD:GEO:IM-1E:U07:L09",
            "PED:US-CCSS-MATH:HS:TRAD:GEO:IM-1E:U08:L01",
        };

    public static bool IsTarget(string lessonCode) =>
        LessonCodes.Contains(lessonCode);

    public static int TargetCount => LessonCodes.Count;
}
