#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/src/Edulytics.Web/wwwroot"
OUT="$ROOT/public-frontdoor/dist"
ORIGIN="https://staging.edulytiks.com"

rm -rf "$OUT"
mkdir -p "$OUT/pl" "$OUT/en" "$OUT/ar"

# Reuse the exact assets used by the live ASP.NET public site.
cp -R "$SRC/." "$OUT/"
cp "$ROOT/public-frontdoor/frontdoor.js" "$OUT/frontdoor.js"

# The public CSS/JS bundles are generated by ASP.NET routes rather than stored
# as physical files, so snapshot those generated bundles as static assets too.
mkdir -p "$OUT/css" "$OUT/js"

echo "Waking the application before taking the public-site snapshot..."
ready=0
for attempt in $(seq 1 60); do
  if curl -fsS --connect-timeout 5 --max-time 10 "$ORIGIN/health/ready" | grep -q '"Healthy"'; then
    ready=1
    break
  fi
  sleep 2
done

if [ "$ready" -ne 1 ]; then
  echo "The staging application did not become ready in time." >&2
  exit 1
fi

curl -fsS --retry 5 --retry-all-errors --retry-delay 2 --max-time 120   "$ORIGIN/css/public-site-v44.css"   -o "$OUT/css/public-site-v44.css"

curl -fsS --retry 5 --retry-all-errors --retry-delay 2 --max-time 120   "$ORIGIN/js/public-site-v45.js"   -o "$OUT/js/public-site-v45.js"

snapshot() {
  local language="$1"
  local target="$2"
  local cookie="Edulytics.Culture=c=${language}|uic=${language}"

  echo "Snapshotting homepage language: $language"
  curl -fsS --retry 5 --retry-all-errors --retry-delay 2 --max-time 120     -H "Cookie: $cookie"     "$ORIGIN/"     -o "$target"

  # Add only the static-front-door behavior. The visual markup, CSS and all
  # existing public-site scripts remain exactly as emitted by ASP.NET.
  sed -i 's#</body>#<script src="/frontdoor.js" defer></script></body>#' "$target"
}

snapshot "pl" "$OUT/pl/index.html"
snapshot "en" "$OUT/en/index.html"
snapshot "ar" "$OUT/ar/index.html"

# Polish remains the public default at the root domain.
cp "$OUT/pl/index.html" "$OUT/index.html"

echo "Exact server-rendered public snapshots built at $OUT"
