#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/src/Edulytics.Web/wwwroot"
OUT="$ROOT/public-frontdoor/dist"
ORIGIN="https://staging.edulytiks.com"
STATIC_FALLBACK_ORIGIN="https://edulytics-public.onrender.com"
SNAPSHOT_ORIGIN="$ORIGIN"
SOURCE_MODE="backend"

rm -rf "$OUT"
mkdir -p "$OUT/pl" "$OUT/en" "$OUT/ar"

# Reuse the exact assets used by the live ASP.NET public site.
cp -R "$SRC/." "$OUT/"
cp "$ROOT/public-frontdoor/frontdoor.js" "$OUT/frontdoor.js"

# The public CSS/JS bundles are generated by ASP.NET routes rather than stored
# as physical files, so snapshot those generated bundles as static assets too.
mkdir -p "$OUT/css" "$OUT/js"

echo "Waking the application before taking public-site snapshots..."
ready=0
for attempt in $(seq 1 8); do
  if curl -fsS --connect-timeout 5 --max-time 10 "$ORIGIN/health/ready" | grep -q '"Healthy"'; then
    ready=1
    break
  fi
  sleep 2
done

if [ "$ready" -ne 1 ]; then
  # The public front door must remain deployable even when the dynamic service
  # or its database is temporarily unavailable. Reuse the last live static
  # snapshots, then inject the new frontdoor runtime and canonical-link fixes.
  echo "Staging is unavailable; rebuilding from the last live static snapshots."
  SNAPSHOT_ORIGIN="$STATIC_FALLBACK_ORIGIN"
  SOURCE_MODE="static"
fi

curl -fsS --retry 5 --retry-all-errors --retry-delay 2 --max-time 120 \
  "$SNAPSHOT_ORIGIN/css/public-site-v44.css" \
  -o "$OUT/css/public-site-v44.css"

curl -fsS --retry 5 --retry-all-errors --retry-delay 2 --max-time 120 \
  "$SNAPSHOT_ORIGIN/js/public-site-v45.js" \
  -o "$OUT/js/public-site-v45.js"

inject_frontdoor_runtime() {
  local target="$1"
  sed -i 's#</body>#<script src="/frontdoor.js" defer></script></body>#' "$target"
}

snapshot_home() {
  local language="$1"
  local target="$2"
  local cookie="Edulytics.Culture=c=${language}|uic=${language}"

  echo "Snapshotting homepage language: $language"

  if [ "$SOURCE_MODE" = "backend" ]; then
    curl -fsS --retry 5 --retry-all-errors --retry-delay 2 --max-time 120 \
      -H "Cookie: $cookie" \
      "$SNAPSHOT_ORIGIN/" \
      -o "$target"
  else
    curl -fsS --retry 5 --retry-all-errors --retry-delay 2 --max-time 120 \
      "$SNAPSHOT_ORIGIN/${language}/" \
      -o "$target"
  fi

  inject_frontdoor_runtime "$target"
}

snapshot_public_route() {
  local route="$1"
  local relative="${route#/}"
  local target="$OUT/$relative/index.html"
  local cookie="Edulytics.Culture=c=pl|uic=pl"

  mkdir -p "$(dirname "$target")"
  echo "Snapshotting public route: $route"

  if [ "$SOURCE_MODE" = "backend" ]; then
    # -L follows intentional public aliases such as /product -> /product/features.
    curl -fsSL --retry 5 --retry-all-errors --retry-delay 2 --max-time 120 \
      -H "Cookie: $cookie" \
      "$SNAPSHOT_ORIGIN$route" \
      -o "$target"
  else
    curl -fsS --retry 5 --retry-all-errors --retry-delay 2 --max-time 120 \
      "$SNAPSHOT_ORIGIN$route/" \
      -o "$target"
  fi

  inject_frontdoor_runtime "$target"
}

snapshot_home "pl" "$OUT/pl/index.html"
snapshot_home "en" "$OUT/en/index.html"
snapshot_home "ar" "$OUT/ar/index.html"

# Polish remains the public default at the root domain.
cp "$OUT/pl/index.html" "$OUT/index.html"

# Every anonymous GET page linked from the public website receives an exact
# server-rendered static snapshot. A direct visit therefore renders immediately
# from Edulytics Public while frontdoor.js wakes the free application in the
# background instead of exposing Render's cold-start page.
PUBLIC_ROUTES=(
  "/product"
  "/teachers"
  "/parents"
  "/schools"
  "/students"
  "/product/learning-built-for-understanding"
  "/product/results-backed-by-data"
  "/product/support-you-can-rely-on"
  "/product/student-portal"
  "/product/assessment-and-practice"
  "/product/mastery-and-next-step"
  "/product/mathematics"
  "/product/curricula"
  "/product/features"
  "/product/edulytics-ai"
  "/product/languages"
  "/product/technical-requirements"
  "/teachers/overview"
  "/teachers/assessment-and-curriculum"
  "/parents/overview"
  "/schools/overview"
  "/students/overview"
  "/company/partnerships"
  "/company/about"
  "/contact"
  "/contact/sales-enquiry"
  "/contact/request-demo"
  "/contact/support"
  "/contact/message"
  "/contact/help"
  "/help"
  "/legal/privacy"
  "/legal/terms"
  "/legal/data-processing-agreement"
  "/legal/content-sources"
  "/account/login"
)

for route in "${PUBLIC_ROUTES[@]}"; do
  snapshot_public_route "$route"
done

# Render serves directory snapshots canonically at paths that end in "/".
# Rewrite every generated internal public link to that canonical form at build
# time so navigation never falls through to a sleeping dynamic service before
# frontdoor.js has a chance to run.
for route in "${PUBLIC_ROUTES[@]}"; do
  canonical="${route}/"
  while IFS= read -r -d '' html; do
    sed -i "s#href=\"${route}\"#href=\"${canonical}\"#g" "$html"
    sed -i "s#href='${route}'#href='${canonical}'#g" "$html"
  done < <(find "$OUT" -type f -name '*.html' -print0)
done

echo "Exact server-rendered public snapshots built at $OUT"
