#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/src/Edulytics.Web/wwwroot"
OUT="$ROOT/public-frontdoor/dist"
ORIGIN="https://edulytics-4346.onrender.com"
STATIC_FALLBACK_ORIGIN="https://edulytics-public.onrender.com"
SNAPSHOT_ORIGIN="$ORIGIN"
SOURCE_MODE="backend"

rm -rf "$OUT"
mkdir -p "$OUT/pl" "$OUT/en" "$OUT/ar"

# Reuse the exact assets used by the live ASP.NET public site.
cp -R "$SRC/." "$OUT/"
cp "$ROOT/public-frontdoor/frontdoor.js" "$OUT/frontdoor.js"

# The public CSS/JS bundles are generated by ASP.NET routes rather than stored
# as physical files, so snapshot those generated bundles as static assets too.
mkdir -p "$OUT/css" "$OUT/js"

echo "Waking the application before taking public-site snapshots..."
ready=0
for attempt in $(seq 1 8); do
  if curl -fsS --connect-timeout 5 --max-time 10 "$ORIGIN/health/ready" | grep -q '"Healthy"'; then
    ready=1
    break
  fi
  sleep 2
done

if [ "$ready" -ne 1 ]; then
  # The public front door must remain deployable even when the dynamic service
  # or its database is temporarily unavailable. Reuse the last live static
  # snapshots, then inject the new frontdoor runtime and canonical-link fixes.
  echo "Main application is unavailable; rebuilding from the last live static snapshots."
  SNAPSHOT_ORIGIN="$STATIC_FALLBACK_ORIGIN"
  SOURCE_MODE="static"
fi

bundle_files() {
  local target="$1"
  shift
  : > "$target"

  for relative in "$@"; do
    printf '/* %s */\n' "$relative" >> "$target"
    cat "$SRC/$relative" >> "$target"
    printf '\n;\n' >> "$target"
  done
}

# Build the generated public bundles directly from repository sources. This is
# the same source order used by PublicAssetBundleController, but it does not
# require the dynamic ASP.NET service to be awake.
PUBLIC_CSS_FILES=(
  "css/round2-product-fixes.css"
  "css/public-home.css"
  "css/round4-ux-display.css"
  "css/public-home-commercial-v4.css"
  "css/public-home-commercial-v5.css"
  "css/public-home-commercial-v6.css"
  "css/public-home-commercial-v10.css"
  "css/public-home-commercial-v11.css"
  "css/public-home-commercial-v12.css"
  "css/public-home-commercial-v13.css"
  "css/public-home-commercial-v14.css"
  "css/public-home-commercial-v15.css"
  "css/public-home-commercial-v16.css"
  "css/public-home-commercial-v17.css"
  "css/public-home-philosophy-v23.css"
  "css/public-contact-v4.css"
  "css/public-contact-system-v28.css"
  "css/public-home-footer-v24.css"
  "css/public-home-navbar-v25.css"
  "css/public-understanding-v1.css"
  "css/public-content-pages-v27.css"
  "css/public-arabic-rtl-v29.css"
  "css/public-home-visual-contract-v32.css"
  "css/public-home-mascot-transparency-v35.css"
)

PUBLIC_JS_FILES=(
  "js/public-home-commercial-v4.js"
  "js/public-home-commercial-v5.js"
  "js/public-home-commercial-v6.js"
  "js/public-home-commercial-v9.js"
  "js/public-home-commercial-v10.js"
  "js/public-home-commercial-v11.js"
  "js/public-home-commercial-v12.js"
  "js/public-home-commercial-v13.js"
  "js/public-home-commercial-v14.js"
  "js/public-home-commercial-v15.js"
  "js/public-home-cartoon-cleanup.js"
  "js/public-home-experience-v20.js"
  "js/public-home-curricula-v21.js"
  "js/public-home-ai-spotlight-v22.js"
  "js/public-site-routing-v27.js"
  "js/public-site-routing-v28.js"
  "js/public-understanding-v1.js"
  "js/public-legal-static-localize-v1.js"
  "js/public-contact-system-v28.js"
)

PUBLIC_CONTENT_JS_FILES=(
  "js/public-content-pages-v27-en.js"
  "js/public-content-pages-v27-pl.js"
  "js/public-content-pages-v27-ar.js"
  "js/public-content-pages-v27.js"
)

bundle_files "$OUT/css/public-site-v44.css" "${PUBLIC_CSS_FILES[@]}"
bundle_files "$OUT/js/public-site-v45.js" "${PUBLIC_JS_FILES[@]}"
bundle_files "$OUT/js/public-content-v33.js" "${PUBLIC_CONTENT_JS_FILES[@]}"

inject_frontdoor_runtime() {
  local target="$1"

  # Fallback snapshots may already contain the previous frontdoor runtime.
  # Remove it before injecting the current runtime so listeners are installed once.
  sed -i 's#<script src="/frontdoor.js" defer></script>##g' "$target"
  # Old cached HTML may retain the retired demo login interceptor.
  # Remove it even when the static build must use cached public snapshots.
  sed -i -E 's#<script[^>]*src="[^"]*/js/unified-demo-login\.js[^"]*"[^>]*></script>##g' "$target"
  sed -i 's#<script data-frontdoor-language-bootstrap>.*</script>##g' "$target"

  # Public content snapshots are Polish by default. Before the bundled public
  # scripts execute, restore the language selected on the static front door so
  # their existing EN/PL/AR client catalogs render the correct copy immediately.
  sed -i 's#<head>#<head><script data-frontdoor-language-bootstrap>(function(){try{var d=document.documentElement;d.dataset.snapshotLanguage=d.lang||"pl";var l=localStorage.getItem("edulytics.frontdoor.language");if(l==="en"||l==="pl"||l==="ar"){d.lang=l;d.dir=l==="ar"?"rtl":"ltr";}}catch(e){}})();</script>#' "$target"

  sed -i 's#</body>#<script src="/frontdoor.js" defer></script></body>#' "$target"
}

snapshot_home() {
  local language="$1"
  local target="$2"
  local cookie="Edulytics.Culture=c=${language}|uic=${language}"

  echo "Snapshotting homepage language: $language"

  if [ "$SOURCE_MODE" = "backend" ]; then
    curl -fsS --retry 5 --retry-all-errors --retry-delay 2 --max-time 120 \
      -H "Cookie: $cookie" \
      "$SNAPSHOT_ORIGIN/" \
      -o "$target"
  else
    curl -fsS --retry 5 --retry-all-errors --retry-delay 2 --max-time 120 \
      "$SNAPSHOT_ORIGIN/${language}/" \
      -o "$target"
  fi

  inject_frontdoor_runtime "$target"
}

snapshot_public_route() {
  local route="$1"
  local relative="${route#/}"
  local target="$OUT/$relative/index.html"
  local cookie="Edulytics.Culture=c=pl|uic=pl"

  mkdir -p "$(dirname "$target")"
  echo "Snapshotting public route: $route"

  if [ "$SOURCE_MODE" = "backend" ]; then
    # -L follows intentional public aliases such as /product -> /product/features.
    curl -fsSL --retry 5 --retry-all-errors --retry-delay 2 --max-time 120 \
      -H "Cookie: $cookie" \
      "$SNAPSHOT_ORIGIN$route" \
      -o "$target"
  else
    curl -fsS --retry 5 --retry-all-errors --retry-delay 2 --max-time 120 \
      "$SNAPSHOT_ORIGIN$route/" \
      -o "$target"
  fi

  inject_frontdoor_runtime "$target"
}

snapshot_home "pl" "$OUT/pl/index.html"
snapshot_home "en" "$OUT/en/index.html"
snapshot_home "ar" "$OUT/ar/index.html"

# Polish remains the public default at the root domain.
cp "$OUT/pl/index.html" "$OUT/index.html"

# Every anonymous GET page linked from the public website receives an exact
# server-rendered static snapshot. A direct visit therefore renders immediately
# from Edulytics Public while frontdoor.js wakes the free application in the
# background instead of exposing Render's cold-start page.
PUBLIC_ROUTES=(
  "/product"
  "/teachers"
  "/parents"
  "/schools"
  "/students"
  "/product/learning-built-for-understanding"
  "/product/results-backed-by-data"
  "/product/support-you-can-rely-on"
  "/product/student-portal"
  "/product/assessment-and-practice"
  "/product/mastery-and-next-step"
  "/product/mathematics"
  "/product/curricula"
  "/product/features"
  "/product/edulytics-ai"
  "/product/languages"
  "/product/technical-requirements"
  "/teachers/overview"
  "/teachers/assessment-and-curriculum"
  "/parents/overview"
  "/schools/overview"
  "/students/overview"
  "/company/partnerships"
  "/company/about"
  "/contact"
  "/contact/sales-enquiry"
  "/contact/request-demo"
  "/contact/support"
  "/contact/message"
  "/contact/help"
  "/help"
  "/legal/privacy"
  "/legal/terms"
  "/legal/data-processing-agreement"
  "/legal/content-sources"
  "/account/login"
)

for route in "${PUBLIC_ROUTES[@]}"; do
  snapshot_public_route "$route"
done

# Render serves directory snapshots canonically at paths that end in "/".
# Rewrite every generated internal public link to that canonical form at build
# time so navigation never falls through to a sleeping dynamic service before
# frontdoor.js has a chance to run.
for route in "${PUBLIC_ROUTES[@]}"; do
  canonical="${route}/"
  while IFS= read -r -d '' html; do
    sed -i "s#href=\"${route}\"#href=\"${canonical}\"#g" "$html"
    sed -i "s#href='${route}'#href='${canonical}'#g" "$html"
  done < <(find "$OUT" -type f -name '*.html' -print0)
done

echo "Exact server-rendered public snapshots built at $OUT"
