#!/usr/bin/env node
// Create original educational six-field REVIEW DRAFTS from verified UAE
// textbook topic titles. No copied textbook paragraphs, no official outcome
// assertions, and NO automatic publication.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const reviewRoot = resolve(process.argv[2] || resolve(here, '../../artifacts/phase29/uae-advanced-review-candidates'));
const outRoot = resolve(process.argv[3] || resolve(here, '../../artifacts/phase29/uae-advanced-authored-drafts'));

const BANK = {
'5:1': ['Mathematical thinking starts by looking for a relationship, representing it clearly, explaining why a strategy works, and comparing alternative solutions.', 'Four trays contain six counters each. The total is 4 × 6 = 24 counters. Another representation is 6 + 6 + 6 + 6 = 24; both models describe the same collection.', 'Identify four equal groups. Draw or count six items in each group. Add four sixes to obtain 24. Use multiplication to confirm the repeated-addition model.', 'An explanation is not just a number: show the chosen representation and how it supports the result.'],
'5:2': ['Volume counts the number of cubic units filling a solid without gaps or overlaps. A rectangular prism has volume length × width × height.', 'A rectangular prism measures 3 cm by 4 cm by 2 cm. Its volume is 3 × 4 × 2 = 24 cm³. Two nonoverlapping prisms of volumes 24 cm³ and 6 cm³ make 30 cm³.', 'Count 3 × 4 = 12 unit cubes in one layer. There are 2 such layers, so 12 × 2 = 24 cm³. Add separate component volumes only when pieces do not overlap.', 'Do not use square centimetres for volume, and do not double-count overlapping pieces.'],
'5:3': ['Each place to the left is ten times the place to its right. A decimal digit represents tenths, hundredths, or thousandths depending on its position.', 'In 6.245, the 2 represents two tenths, the 4 represents four hundredths, and the 5 represents five thousandths. Rounded to the nearest hundredth, 6.245 becomes 6.25.', 'Locate the hundredths digit 4, then inspect the thousandths digit 5. Increase the hundredths digit by one and keep the remaining place values unchanged.', 'Comparing decimals by counting digits is unreliable: 0.7 is greater than 0.65 even though 0.65 has more digits.'],
'5:4': ['Addition and subtraction of decimals preserve place value. Align the decimal points and estimate before calculating to assess reasonableness.', 'Compute 3.45 + 2.70 = 6.15. For subtraction, 7.80 − 2.46 = 5.34. Rounding to the nearest whole number provides a quick plausibility check.', 'Write each number with digits aligned by place value. Add 3.45 and 2.70 from hundredths to ones. For subtraction, regroup where necessary and verify with addition.', 'Do not align the last digits instead of decimal points. Missing trailing zeros do not change a decimal value.'],
'5:5': ['Multiplication can be decomposed using place value and the distributive property. Partial products and area models should give the same total.', 'Calculate 24 × 13 as (20 + 4) × (10 + 3). The partial products are 200, 60, 40, and 12; the sum is 312. This matches 24 × (10 + 3) = 240 + 72.', 'Split each factor into tens and ones. Multiply each pair of components. Add the partial products and check that the result is close to the estimate 24 × 10.', 'Forgetting a partial product or the place value of a tens digit can change the answer by a factor of ten.'],
'5:6': ['Decimal multiplication follows whole-number multiplication together with careful placement of decimal digits and a reasonableness estimate.', 'For 1.2 × 0.3, calculate 12 × 3 = 36 and account for two decimal places to obtain 0.36. This is less than 1.2, as expected when multiplying by 0.3.', 'Ignore decimal points temporarily and multiply 12 by 3. Count the two decimal places across both original factors and write 0.36. Compare with an estimate.', 'Placing the decimal point without estimating can turn the correct answer 0.36 into 3.6 or 36.'],
'5:7': ['Division and multiplication are inverse operations. Estimate a quotient and use multiplication to verify that the quotient and divisor reproduce the dividend.', 'For 864 ÷ 24, notice 24 × 36 = 864, so the quotient is 36. Using partial quotients, 24 × 30 = 720 and 24 × 6 = 144; together they total 864.', 'Estimate using 864 ÷ 20. Subtract 720, then 144, tracking the partial quotients 30 and 6. Add those quotients to obtain 36 and multiply back to check.', 'Forgetting to include a partial quotient or checking with addition instead of multiplication can hide an incorrect answer.'],
'5:8': ['When dividing decimals, preserve the quotient by multiplying both dividend and divisor by the same power of ten until the divisor is whole.', 'Calculate 12.6 ÷ 0.3 by multiplying both values by 10: 126 ÷ 3 = 42. Verify because 0.3 × 42 = 12.6. The scaling changes neither ratio nor quotient.', 'Choose a power of ten making 0.3 a whole number. Scale both numbers by 10, divide 126 by 3, and verify the original operation through multiplication.', 'Scaling only the divisor changes the quotient. The dividend and divisor must be scaled together.'],
'5:9': ['To add or subtract fractions with unlike denominators, express them as equivalent fractions with a common denominator before combining their numerators.', 'Calculate 2/3 + 1/4. Use denominator 12: 8/12 + 3/12 = 11/12. For 1 1/2 − 3/4, convert 1 1/2 to 6/4 and subtract to obtain 3/4.', 'Find a common multiple of the denominators. Replace each fraction with an equivalent one. Combine the numerators, preserve the denominator, and simplify.', 'Adding denominators directly is incorrect: 1/2 + 1/3 is 5/6, not 2/5.'],
'5:10': ['Fraction multiplication combines parts of parts. Multiply numerators together and denominators together, then simplify where possible.', 'Calculate (2/3) × (3/4) = 6/12 = 1/2. A rectangle with fractional side lengths 1/2 m and 3/5 m has area 3/10 square metres.', 'Interpret each factor as a fractional share. Multiply numerators 2 × 3 and denominators 3 × 4. Simplify 6/12 to 1/2 and check that the product is sensible.', 'Unlike fraction addition, multiplication does not require common denominators.'],
'5:11': ['Dividing by a fraction asks how many fractional units fit into a quantity. Multiplying by the reciprocal gives the same quotient when the divisor is nonzero.', 'Compute 3 ÷ (1/4) = 12 because twelve quarters make three wholes. For (3/4) ÷ (1/2), multiply 3/4 by 2 to obtain 3/2 or 1 1/2.', 'Represent the dividend as a collection of fractional units. Count how many divisor-sized pieces fit. Then verify using multiplication by the reciprocal.', 'Dividing by zero is undefined; also, do not invert the dividend when using reciprocal multiplication.'],
'5:12': ['Measurement requires identifying the original unit and using a conversion factor. Line plots summarize repeated measurements along a labelled number line.', 'Since 1 m = 100 cm, a 2.5 m length is 250 cm. Since 1 ft = 12 in, 3 ft = 36 in. For repeated lengths of 1/2 m, record one mark per observation.', 'Write the known unit relationship. Multiply or divide according to the direction of conversion, attach the new unit, and check whether the size is reasonable.', 'Confusing a linear unit with a square or cubic unit produces incorrect conversion factors.'],
'5:13': ['Coordinate pairs show horizontal and vertical positions. Shapes can be classified by defining side, angle, and parallel-line properties.', 'Plot the point (2, 3) by moving two units along the horizontal axis and three units up. A square has four equal sides and four right angles, making it a rectangle as well.', 'Read the x-coordinate first and locate the horizontal position. Then use the y-coordinate. To classify a polygon, test the stated geometric properties.', 'Swapping coordinate order gives a different point; visual appearance alone cannot replace geometric definitions.'],
'5:14': ['Numerical expressions encode operations and their order. Patterns can be described by rules and checked by evaluating several inputs.', 'Evaluate 3 × (4 + 2) = 18. A sequence 3, 5, 7, 9 follows the rule 2n + 1 for n = 1, 2, 3, 4, where n records the position.', 'Evaluate brackets first to obtain 6, then multiply by 3. For the pattern, test the rule at several positions and check each expected term.', 'Ignoring parentheses or confusing a term number with the term value changes an expression or a pattern rule.'],
'6:1': ['A ratio compares quantities multiplicatively, while a unit rate specifies a quantity per single unit of another measure.', 'For a ratio of 2 red tokens to 3 blue tokens, multiplying each part by 2 gives the equivalent ratio 4:6. Travelling 12 km in 3 hours yields 4 km per hour.', 'Identify the two quantities and their units. Scale both sides of a ratio together, or divide the measured quantity by the number of units to find a unit rate.', 'Adding the same number to both ratio terms generally does not preserve the ratio; scale both terms by a common factor.'],
'6:2': ['Percent means per hundred. Fractions, decimals, and percents express the same proportional quantity in different forms.', 'Three quarters equals 3 ÷ 4 = 0.75 = 75%. Thirty percent of 60 equals 0.30 × 60 = 18. If 18 is 30% of a whole, the whole is 18 ÷ 0.30 = 60.', 'Convert the percent to a decimal by dividing by 100. Multiply by the whole to find a part, or divide a part by its decimal rate to recover the whole.', 'For 30%, using 30 instead of 0.30 overstates the part by a factor of 100.'],
'6:3': ['Accurate multi-digit arithmetic depends on place value, equivalent forms, and checks using inverse operations.', 'Divide 936 by 12: the quotient is 78 because 12 × 78 = 936. Compute 12.5 ÷ 0.5 = 25. Also, (2/3) ÷ (1/4) = 8/3 = 2 2/3.', 'Estimate first, then use an algorithm or equivalent expression. Scale decimal divisors consistently; invert a nonzero fractional divisor; verify the result.', 'Do not shift only one decimal in division, and do not add denominators when dividing fractions.'],
'6:4': ['Integers extend number systems below zero; rational numbers also include fractions and terminating or repeating decimals. Coordinate signs locate quadrants.', 'The opposite of −3 is 3, and |−4| = 4. The distance between −5 and 2 on a number line is |−5 − 2| = 7. The point (2, −3) lies in quadrant IV.', 'Mark zero on a number line, then move in the direction of each sign. Find distance by subtracting positions and taking absolute value.', 'Absolute value represents distance from zero, so it is nonnegative; confusing signs may move a point to the wrong quadrant.'],
'6:5': ['An algebraic expression represents a numerical relationship using variables, operations, parentheses, and properties such as distribution.', 'For x = 3, evaluate 5x + 2 = 17. Expand 3(x + 4) to obtain 3x + 12. Evaluate 3² + 4 = 13 by applying the exponent before addition.', 'Substitute each given value in parentheses. Follow order of operations. When expanding brackets, multiply each term by the outside factor and combine like terms.', 'The expression 3(x + 4) is not 3x + 4; the factor 3 must multiply both terms.']
};
const mins={explanation:80,keyConceptsAndRules:60,workedExamples:120,stepByStepSolutions:80,commonMistakes:60,quickSummary:60};
mkdirSync(outRoot,{recursive:true});
let total=0;
for (const filename of ['uae-g5-advanced-volume1-review.json','uae-g5-advanced-volume2-review.json','uae-g6-advanced-volume1-module1to5-review.json']) {
  const data=JSON.parse(readFileSync(resolve(reviewRoot,filename),'utf8'));
  for(const lesson of data.lessons){
    const unit=Number(lesson.sourceLessonNumber.split('-')[0]);
    const parts=BANK[`${data.grade}:${unit}`];
    if(!parts)throw Error(`Missing authored unit reference for grade ${data.grade} unit ${unit}`);
    const [concept,worked,steps,mistake]=parts;
    const title=lesson.title;
    lesson.pedagogicalDraft={
      cultureCode:'en',
      explanation:`This lesson explores ${title} within ${lesson.unitTitle}. ${concept} The task is to connect the representation to a correct mathematical reason.`,
      keyConceptsAndRules:`${concept} Apply the principle specifically to ${title}, and check each quantity and its units.`,
      workedExamples:`Original Edulytics example related to the unit of ${lesson.unitTitle}: ${worked} Use the mathematical structure to explain how ${title} connects to this example.`,
      stepByStepSolutions:`${steps} Finally, decide whether the result is consistent with the original quantities.`,
      commonMistakes:`${mistake} In ${title}, use estimation or a reverse-operation check before accepting an answer.`,
      quickSummary:`${title}: ${concept} Record the general principle and one independent check.`
    };
    for(const [field,min]of Object.entries(mins))if(lesson.pedagogicalDraft[field].length<min)throw Error(`Draft field too short: ${title} / ${field}`);
    lesson.contentStatus='MATH_REVIEW_REQUIRED';
    lesson.authorizedForPublication=false;
    total++;
  }
  data.isPublishable=false;
  data.requiresHumanMathematicsAndRightsReview=true;
  writeFileSync(resolve(outRoot,filename.replace('-review.json','-authored-draft.json')),JSON.stringify(data,null,2)+'\n','utf8');
}
console.log(`UAE_ADVANCED_AUTHORED_DRAFTS_PASS: ${total} lesson drafts; six pedagogical fields each; NO publication`);
